FROM python:3.12-alpine

ARG MEDIA_PIPELINE_VERSION=0.2.0
ARG MEDIA_PIPELINE_REVISION=unknown

WORKDIR /app
COPY app/ /app/

ENV PYTHONUNBUFFERED=1
ENV MEDIA_PIPELINE_VERSION=${MEDIA_PIPELINE_VERSION}
ENV MEDIA_PIPELINE_REVISION=${MEDIA_PIPELINE_REVISION}
ENTRYPOINT ["python", "-m", "pipeline.bot"]
