FROM python:3.12-alpine

ARG MEDIA_PIPELINE_VERSION=0.1.0
ARG MEDIA_PIPELINE_REVISION=unknown

WORKDIR /app
COPY app/ /app/
RUN pip install --no-cache-dir "psycopg[binary]>=3.2,<4" "Pillow>=10,<12"

ENV PYTHONUNBUFFERED=1
ENV MEDIA_PIPELINE_VERSION=${MEDIA_PIPELINE_VERSION}
ENV MEDIA_PIPELINE_REVISION=${MEDIA_PIPELINE_REVISION}
ENTRYPOINT ["python", "-m", "pipeline.cli"]
CMD ["folders"]
